echo off
color a
cls



echo ..................................................
echo ...........   PZZZZZZ         ....................
echo ........  .?J?5PPPPPY???????JZ      ..............
echo ........::^Z@@Z:^^^:P@@@@@@@@P.:::::..............
echo ...... :ZHZZHH::::::^HHHHHHHHJ@HHH@B.  ...........
echo .....  :H@@Z^^:::::::::::::::HYYYYYYYYY.  ........
echo .....^^HBZBH^^:::::::::::::::::::::HZHZH^^........
echo ... ^H@ZH^^:::::::::::::::::::::::::^^HH@@^   ....
echo ... ^@@HH^^:::^^^^^^^^^^^^:.::::::::::^?JJ5PP^ ...
echo ... ^@@HH^^:::^^^^^^^^^^^^^::::::::::::^^^Z@@H ...
echo ..  ^@@HH^^:::::::::::::::^HHHHHHHH^:::^^^Z@@H  ..
echo  HBGB@@H^^^:::::::::::::::^^^^:::^^^^^^^^^Z@@BGBZ 
echo  Z@@@GGGJJ?^:::::7??H::::::::H??7::^^^H?JJPGGH@@7 
echo  Z@@ZHHZH@HH:::::G@@J::::::::?@@B:::::^H@@7HHB@@7 
echo  Z@@ZHHHZZZ^:::::B@@J::::::::?@@Z:::::^ZZZHHHZ@@7 
echo  ^YYY55555YH^^^::J55Z::::::::Z55J::^^^^Y55555YYY^ 
echo .   ^HHHHHH7ZZ^^^:::^HHHHHHHH^:::^^^ZZ7ZHHHHHH   .
echo .....::::::Z@@7^H^::5@@@@@@@@P::^H^ZH@H^.::::.....
echo .....     .7??5PPZ^^?YYYYYYYY?^^ZPP5??7.     .....
echo ...........:^^B@@Y77777777777777J@@Z^^:...........
echo ........  .Z@@GGGH@@@@@@@@@@@@@@HGGG@@H:   .......
echo ....   .PGGBBB?ZZYPPGBBBBBBBBBPP5ZZ7BBBGGP:   ....
echo ... .ZZ7BZB555?77?JJJYYYYYYYYYJJ?77?555BBB7ZZ: ...
echo ... ^@@HZHHZ77Z@@YZ7H^^^^^^^^H7ZJ@@H77ZHHHZ@@H ...
echo  HBBG??7^^^GZZBGGYJJJ????????JJJYGGBZZBH^^7??PBBZ 
echo  Z@@ZHHH::^H@@BGGP55555PPPP55555PGGB@@HH::^HHB@@7 
echo  H@@BZHH^^HZ@@ZZZBBBBBBZZZZBBBBBBZZZ@@HH^^HZHB@@Z 
echo  .^:ZHHHHHHZZZBBBBBBBZZH@@HZZZBBBBBBZZZHHHHHH7:^. 
echo .   :YYYYJYZHH5JJJJ?GHH@@@@HHB?JJJJYHHHYJYYYY:   .
echo ....    ..:BHH7HH^^^P@@HZZH@@G^^^HH7ZHZ^.:    ....
echo ...... :H@HZ^^JYYYYYZ@@Y..J@@ZYYYJJ?^^HH@H^ ......
echo ...... .7??PPPBZZZZZ57?^  ^?7YZZZZZBPPP???: ......
echo ........  .GZBBBBBBZZ   ..   HBBBBBBBZG.   .......
echo ..................................................

pause